//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CooperDemo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int GetAllTaskFoldersButton = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int TaskFolderId = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int TaskFolderName = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int icon = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int list = 2131034113;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskFolderListItem = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int GetAllTaskFolders = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GetLocalTaskFolders = 2130968577;
			
			private String()
			{
			}
		}
	}
}
