//Copyright (c) CodeSharp.  All rights reserved. - http://www.icodesharp.com/

//moment组件语言设置
//moment.lang('zh-cn');

//简易提供文案
var lang = {};
lang.work_in_cooper = 'WORK IN COOPER';
lang.suffix = '- WORK IN COOPER - OpenSource Task Base Platform';
lang.sorry_error_occur_retry_later = '抱歉，发生错误，请稍后再试';
lang.today = '今天';
lang.batch_task = '个任务';
lang.archive = '归档';

lang.comming_soon = '近期推出';
lang.confirm_delete_taskFolder = '确定要删除当前任务表？任务表中的任务也将一起删除';
lang.share_description = '\n\n - 我的任务 - Work IN Cooper';
lang.remove_from_project = '移除该项目';

lang.my_task = '个人任务';
lang.my_profile = '我的设置';
lang.my_team = '我的团队(BETA)';
lang.add_team = '新建团队';
lang.add_project = '新建项目';
lang.add_member = '添加成员';
lang.members = '成员';
lang.n_members = '位成员';
lang.settings = '设置';
lang.email = '邮箱';
lang.nick = '昵称';
lang.send_invite = '发送邀请';
lang.team_current_have = '团队当前有';
lang.team_name = '团队名称：';
lang.submit = '提交';
lang.deal_success = '操作成功';
lang.my_team_task = '我的团队任务';
lang.inbox = '收件箱';
lang.new_project_name = '新建项目';
lang.duplicate_email_in_team = '邮箱地址已经存在';
lang.delete_project = '删除该项目';
lang.dot_not_have_any_teams = '您尚未拥有任何团队信息，请先创建';
lang.confirm_delete_project = '确定要删除当前项目？设置了该项目的任务将会移除此项目设置';
lang.confirm_delete_member = '确定要将该成员从团队中移除？已经分配给该成员的任务将被收回';
lang.member_name = '您在团队中的昵称：';
lang.member_email = '您在团队中的邮箱：';
lang.member_profile = '个人设置';
lang.cancel = '取消';
lang.comment = '评论';
lang.comment_must_more_than_5 = '评论字数至少5个字符';
lang.comment_must_less_than_500 = '评论字数不能超过500';
lang.create_task = '创建了任务';
lang.tags = '标签';
lang.remove_tag_from_task = '移除该标签';

lang.my_task = '个人任务';
lang.my_profile = '我的设置';
lang.myteam = '我的团队';
lang.add_team = '新建团队';
lang.error_occur = '发生错误';
lang.webSiteSuffix = '- WORK IN COOPER - OpenSource Task Management';
lang.team = '团队';
lang.add_project = '新建项目';
lang.add_member = '添加成员';
lang.error_and_retry_later = '错误，请稍后再试';
lang.task_deleted = '个任务已删除，';
lang.revoke = '撤销';
lang.more = '更多';
lang.print = '打印';
lang.by_priority_title = '以优先级排序方式查看任务';
lang.priority = '优先级';
lang.by_dueTime_title = '以截止时间排序查看任务';
lang.time = '时间';
lang.archive = '归档';
lang.archive_finish = '归档已完成的任务';
lang.hide_archive = '隐藏归档任务';
lang.show_archive = '显示归档任务';
lang.addNew = '新建';
lang.complete = '完成';
lang.sort = '调整顺序';
lang.mouse = '鼠标';
lang.select_inverse = '多选/反选';
lang.lose_conn = '与Cooper失去连接';
lang.retry_lose_conn = '请您稍后再试...';
lang.priority_today = '尽快完成';
lang.priority_upcoming = '稍后完成';
lang.priority_later = '迟些再说';
lang.share_to = '分享到';
lang.assignee = '执行人';
lang.project = '项目';
lang.priority_title = '指定任务希望在何时处理';
lang.dueTime = '截止日期';
lang.mobi_install = '客户端安装';
lang.download_address = '下载地址';
lang.web_analysis = ' ';
lang.back = '返回';
lang.detail = '详情';
lang.del='删除';